 version: '3'

 services:
   db:
     image: mysql:latest
     volumes:
       - ./SQL_scripts:/docker-entrypoint-initdb.d/
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=trade_db
       - MYSQL_USER=radu
       - MYSQL_PASSWORD=radu
     ports:
       - 3306:3306
   web:
     image: docker-http
     depends_on:
       - db
     ports:
       - 8080:8080
     environment:
       - DATABASE_NAME=trade_db 
       - DATABASE_HOST=db
       - DATABASE_PORT=3306
       - DATABSE_PASSWORD=radu        